---
title: Exam 1 review
subtitle: Suggested answers
execute:
  echo: false
---

1.  b, c, f, g -

    -   The `blizzard_salary` dataset has 409 rows.

    -   The `percent_incr` variable is numerical and continuous.

    -   The `salary_type` variable is categorical.

2.  b - There is more variability around the mean compared to the hourly distribution.

3.  a, b, e - Pie charts and waffle charts are for visualizing distributions of categorical data only.
    Scatterplots are for visualizing the relationship between two numerical variables.

4.  c - `mutate()` is used to create or modify a variable.

5.  a - `"Poor", "Successful", "High", "Top"`

6.  b - Option 2.
    The plot in Option 1 shows the number of employees with a given performance rating for each salary type while the plot in Option 2 gives the proportion of employees with a given performance rating for each salary type.
    In order to assess the relationship between these variables (e.g., how much more likely is a Top rating among Salaried vs. Hourly workers), we need the proportions, not the counts.

7.  There may be some `NA`s in these two variables that are not visible in the plot.

8. The proportions under Hourly would go in the Hourly bar, and those under Salaried would go in the Salaried bar.

9. c - `filter(salary_type != "Hourly" & performance_rating == "Poor")` - There are 5 observations for **"not Hourly"** **"and"** Poor.

10. a - `arrange()` - The result is arranged in increasing order of `annual_salary`, which is the default for `arrange()`.

11. Part 1: The following should be fixed:

    -   There should be spaces after commas in the code

    -   There should be spaces on both sides of `=` in the code

    -   There should be a space before `+`

    -   `geom_boxplot()` should be on the next line and indented

    -   There should be a `+` at the end of the `geom_boxplot()` line

    -   `labs()` should be indented

    Part 2: The warning is caused by `NA` in the data.
    It means that 39 observations were `NA`s and are not plotted/represented on the plot.

12.  d

13.  a, d

14.  a, d

15.  c

16.  b

17.  a

18.  b

19.  

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-asp: 0.35
#| fig-width: 7

library(tidyverse)

tv <- read_csv("data/tv.csv")
law_and_order <- tv |>
  filter(str_detect(title, "Law & Order"))

ggplot(law_and_order, aes(x = season, y = av_rating, shape = title)) +
  geom_line(linewidth = 0.3) +
  geom_point(size = 3) +
  scale_shape_manual(
    values = c(
      "Law & Order: SVU" = "triangle",
      "Law & Order: Criminal Intent" = "diamond",
      "Law & Order: True Crime" = "square",
      "Law & Order" = "asterisk",
      "Law & Order: LA" = "circle"
    )
  ) +
  labs(
    x = "Season",
    y = "Average rating",
    shape = "Series title"
  ) +
  theme(legend.key.height = unit(1.5, "cm"))
```

20.  a, d

21. c, e

22. a

23. a, b, c, d

24. a, d
